debug:
  max_files_to_process: 5
  progress_interval: 1
  timing_threshold: 0.5
inputs:
  directories: 
    - "../output"
  files: []
output:
  directory: test_output
pdf:
  fallback_strategies:
  - direct_file_open
  - pdftotext_command
  skip_patterns: []
processing:
  max_workers: 1
  slow_file_threshold: 2.0
  timeout_per_file: 30
  convert_formulas: false
  remove_latexit: false
  max_file_size_mb: 5.0
  max_content_mb: 1.0
