# Pattern Sets Configuration
# =========================
# Optimized pattern definitions for MVP-Fusion
# Separated by engine type for maximum performance

# Aho-Corasick Keywords (Simple String Matching)
# ===============================================
# These are processed at 50M+ chars/sec with AC automaton

aho_corasick_patterns:
  # Safety and Compliance Keywords
  safety_keywords:
    - "safety"
    - "hazard"
    - "risk"
    - "danger"
    - "warning"
    - "caution"
    - "emergency"
    - "accident"
    - "incident"
    - "injury"
    - "fatality"
    - "compliance"
    - "regulation"
    - "standard"
    - "requirement"
    - "mandatory"
    - "prohibited"
    - "restricted"
    - "approved"
    - "certified"
    
  # Regulatory Organizations
  organizations:
    - "OSHA"
    - "EPA"
    - "NIOSH"
    - "FDA"
    - "NFPA"
    - "ANSI"
    - "ISO"
    - "DOT"
    - "FAA"
    - "CDC"
    - "MSHA"
    - "CPSC"
    
  # Domain-Specific Terms
  workplace_safety:
    - "PPE"
    - "personal protective equipment"
    - "hard hat"
    - "safety glasses"
    - "respirator"
    - "harness"
    - "lockout"
    - "tagout"
    - "LOTO"
    - "confined space"
    - "fall protection"
    - "scaffolding"
    - "ladder safety"
    - "excavation"
    - "trenching"
    
  environmental:
    - "pollution"
    - "contamination"
    - "emission"
    - "discharge"
    - "waste"
    - "recycling"
    - "environmental impact"
    - "air quality"
    - "water quality"
    - "soil contamination"
    - "groundwater"
    - "hazardous material"
    - "toxic"
    - "carcinogen"
    
  medical:
    - "exposure"
    - "dose"
    - "threshold"
    - "limit"
    - "permissible"
    - "occupational health"
    - "industrial hygiene"
    - "ergonomics"
    - "repetitive strain"
    - "noise exposure"
    - "hearing protection"
    - "respiratory protection"

# FLPC Rust Regex Patterns (Complex Pattern Matching)  
# ===================================================
# These are processed at 69M chars/sec with FLPC

flpc_regex_patterns:
  # Universal Entities (Complex Patterns)
  universal_entities:
    money:
      pattern: '(?i)(?:[\$£€¥₹₽₩₪₦₨₱₡₵₴₸₿]\s*\d+(?:[,\.]\d+)*(?:\.\d{2})?|\b\d+(?:[,\.]\d+)*(?:\.\d{2})?\s*(?:dollars?|usd|pounds?|gbp|euros?|eur|yen|jpy|yuan|cny|rupees?|inr|rubles?|rub|won|krw|shekels?|ils|naira?|ngn|pesos?|mxn|php|colones?|crc|cedis?|ghs|hryvnia|uah|tenge|kzt|bitcoin|btc|satoshis?)\b)'
      description: "International currencies with word boundaries"
      priority: high
      
    date:
      pattern: '(?i)\b(?:(?:january|february|march|april|may|june|july|august|september|october|november|december|jan|feb|mar|apr|may|jun|jul|aug|sep|oct|nov|dec)\s+\d{1,2}(?:st|nd|rd|th)?,?\s*\d{4}|\d{1,2}[\/\-\.]\d{1,2}[\/\-\.]\d{2,4}|\d{4}[\/\-\.]\d{1,2}[\/\-\.]\d{1,2})\b'
      description: "International date formats with word boundaries"
      priority: high
      
    email:
      pattern: '\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,}\b'
      description: "Email addresses"
      priority: medium
      
    phone:
      pattern: '(?i)(?:\+?\d{1,3}[\s.-]?)?(?:\(?\d{2,4}\)?[\s.-]?)?\d{3,4}[\s.-]?\d{3,4}(?:\s*(?:x|ext\.?|extension)\s*\d{1,6})?'
      description: "Phone numbers with international formats and extensions"
      priority: medium
      
    percent:
      pattern: '(?i)\b\d{1,3}(?:\.\d{1,2})?%'
      description: "Percentage values"
      priority: medium
      
    time:
      pattern: "(?i)\\b(?:\\d{1,2}:\\d{2}(?::\\d{2})?\\s*(?:am|pm|a\\.m\\.|p\\.m\\.)?|\\d{1,2}\\s*(?:am|pm|a\\.m\\.|p\\.m\\.|o'clock|hours?|hrs?|h))\\b"
      description: "International time formats with word boundaries"
      priority: high
      
    url:
      pattern: '(?i)(?:https?://|www\.)[^\s<>"{}|\\\\^`\\[\\]]+'
      description: "URLs and web links including bare www"
      priority: medium
      
    version:
      pattern: '\bv?\d+\.\d+(?:\.\d+)?(?:-[a-zA-Z0-9]+)?'
      description: "Version numbers"
      priority: low
      
    # Split measurement patterns by category for optimal FLPC performance
    measurement_length:
      pattern: '(?i)\b\d+(?:\.\d+)?\s*(?:millimeters?|millimetres?|mm|centimeters?|centimetres?|cm|meters?|metres?|m|kilometers?|kilometres?|km|inches?|inch|in|feet|foot|ft|yards?|yd|miles?|mi|nautical\s+miles?|nmi|fathoms?|fm|chains?|ch|rods?|rd|furlongs?|fur|leagues?|angstroms?|å|micrometers?|micrometres?|μm|nanometers?|nanometres?|nm|light\s+years?|ly|parsecs?|pc|astronomical\s+units?|au)\b'
      description: "Clean length measurements with word boundaries (true clean separation)"
      priority: medium
      
    measurement_weight:
      pattern: '(?i)\b\d+(?:\.\d+)?\s*(?:milligrams?|mg|grams?|grammes?|g|kilograms?|kilogrammes?|kg|metric\s+tons?|metric\s+tonnes?|t|ounces?|oz|pounds?|lbs?|lb|stones?|st|tons?|tonnes?|short\s+tons?|long\s+tons?|carats?|ct|grains?|gr|drams?|dr|pennyweights?|dwt|troy\s+ounces?|troy\s+pounds?|slugs?)\b'
      description: "Clean weight measurements with word boundaries (true clean separation)"
      priority: medium
      
    measurement_time:
      pattern: '(?i)\b\d+(?:\.\d+)?\s*(?:nanoseconds?|ns|microseconds?|μs|milliseconds?|ms|seconds?|secs?|s|minutes?|mins?|m|hours?|hrs?|h|days?|d|weeks?|wks?|w|months?|mos?|years?|yrs?|y|decades?|centuries?|millennia?|fortnights?)\b'
      description: "Clean time measurements with word boundaries (true clean separation)"
      priority: medium
      
    measurement_temperature:
      pattern: '(?i)\b\d+(?:\.\d+)?\s*(?:degrees?\s*(?:celsius|centigrade|fahrenheit|kelvin)|°\s*(?:c|f|k)|degc|degf|degk|°c|°f|°k)\b'
      description: "Clean temperature measurements with word boundaries (true clean separation)"
      priority: medium
      
    measurement_sound:
      pattern: '(?i)\b\d+(?:\.\d+)?\s*(?:decibels?|db|dba|dbc|sones?)\b'
      description: "Clean sound measurements with word boundaries (true clean separation)"
      priority: medium
      
    measurement_percentage:
      pattern: '(?i)\b\d+(?:\.\d+)?\s*%'
      description: "Percentage measurements with word boundaries (handles ranges like 10-15%)"
      priority: medium
      
    # Range-aware measurement patterns for compound measurements
    measurement_length_range:
      pattern: '(?i)\b(?:-?\d+(?:\.\d+)?)\s*(?:[-–—]\s*\d+(?:\.\d+)?)?\s*(?:millimeters?|millimetres?|mm|centimeters?|centimetres?|cm|meters?|metres?|m|kilometers?|kilometres?|km|inches?|inch|in|feet|foot|ft|yards?|yd|miles?|mi)\b'
      description: "Range-aware length measurements (handles 30-37 inches)"
      priority: high
      
    measurement_temperature_range:
      pattern: '(?i)\b-?\d+(?:\.\d+)?\s*(?:degrees?\s*(?:celsius|fahrenheit|kelvin)|°\s*(?:c|f|k)|°c|°f|°k)\s*(?:(?:to|through|[-–—])\s*-?\d+(?:\.\d+)?\s*(?:degrees?\s*(?:celsius|fahrenheit|kelvin)|°\s*(?:c|f|k)|°c|°f|°k))?\b'
      description: "Range-aware temperature measurements (handles -20°F to 120°F)"
      priority: high
      
    range_indicator:
      pattern: '(?i)\b(?:to|through|between|and)\b|[-–—]'
      description: "Range indicators for proximity-based range detection"
      priority: low
      
      
    regulation:
      pattern: '(?i)\b\d{1,2}\s*CFR\s*\d{3,4}(?:\.\d+)?(?:\([a-z0-9]+\))*(?:\s*Part\s*\d+)?|\b(?:ISO|IEC)\s*\d{4,5}(?::\d{4})?(?:/[A-Z]\d+)?|\bANSI\s*[A-Z]\d+(?:\.\d+)?(?::\d{4})?|\bNFPA\s*\d+[A-Z]?|\bOSHA\s*\d{4}-[A-Z0-9-]+|\bDOT\s*\d+\s*CFR\s*\d+|\bFDA\s*\d+\s*CFR\s*\d+'
      description: "Comprehensive regulation patterns including ISO, NFPA, ANSI, OSHA, and CFR Part forms"
      priority: high

# Pattern Performance Configuration
# ================================

pattern_performance:
  # Engine assignment strategy
  assignment_strategy:
    # Route based on pattern complexity
    simple_keywords: "aho_corasick"      # Simple string matching
    complex_regex: "flpc_rust"           # Complex regex patterns
    fallback: "python_re"                # Compatibility fallback
    
  # Performance optimization
  optimization:
    # Pre-compilation
    precompile_all: true                 # Compile all patterns at startup
    compile_timeout_seconds: 30          # Max compilation time
    
    # Caching
    enable_pattern_cache: true
    cache_size_patterns: 1000            # Cache 1000 compiled patterns
    cache_ttl_minutes: 60                # 1 hour cache TTL
    
    # Parallel processing
    parallel_pattern_execution: true
    max_parallel_patterns: 8             # Process 8 patterns simultaneously
    
  # Pattern routing rules
  routing_rules:
    # Content-based routing
    content_analysis:
      keyword_density_threshold: 0.8     # 80% keywords -> AC
      regex_complexity_threshold: 0.3    # 30% complex -> FLPC
      
    # Performance-based routing  
    performance_routing:
      prefer_fastest: true                # Always prefer fastest engine
      fallback_on_timeout: true          # Fallback if pattern times out
      timeout_ms: 100                     # 100ms pattern timeout
      
    # Quality-based routing
    quality_routing:
      maintain_accuracy: true             # Don't sacrifice accuracy for speed
      accuracy_threshold: 0.98            # 98% minimum accuracy

# Pattern Set Selection
# ====================

pattern_sets:
  # Default pattern set (balanced performance/coverage)
  default:
    aho_corasick: 
      - safety_keywords
      - organizations
      - workplace_safety
    flpc_regex:
      - money
      - date
      - email
      - regulation
      
  # Minimal pattern set (maximum speed)
  minimal:
    aho_corasick:
      - safety_keywords
      - organizations
    flpc_regex:
      - money
      - date
      
  # Complete pattern set (maximum coverage)
  complete:
    aho_corasick:
      - safety_keywords
      - organizations  
      - workplace_safety
      - environmental
      - medical
    flpc_regex:
      - money
      - date
      - email
      - phone
      - percent
      - time
      - url
      - version
      - measurement_length
      - measurement_weight
      - measurement_time
      - measurement_temperature
      - measurement_sound
      - measurement_percentage
      - measurement_length_range
      - measurement_temperature_range
      - range_indicator
      - regulation
      
  # Domain-specific pattern sets
  osha_focused:
    aho_corasick:
      - safety_keywords
      - workplace_safety
    flpc_regex:
      - regulation
      - measurement
      
  environmental_focused:
    aho_corasick:
      - environmental
      - organizations
    flpc_regex:
      - measurement
      - regulation