# Performance Targets Configuration
# =================================
# Aggressive performance benchmarks for MVP-Fusion

# Overall Pipeline Targets
pipeline_targets:
  # Conservative targets (Tier 1 Success)
  conservative:
    pages_per_sec: 4000          # 20x improvement over MVP-Hyper
    documents_per_hour: 14400000  # 4000 * 3600
    memory_efficiency: "50% reduction"
    
  # Aggressive targets (Tier 2 Success)  
  aggressive:
    pages_per_sec: 10000         # 50x improvement
    documents_per_hour: 36000000  # 10000 * 3600
    memory_efficiency: "70% reduction"
    
  # Extreme targets (Tier 3 Success)
  extreme:
    pages_per_sec: 50000         # 250x improvement
    documents_per_hour: 180000000 # 50000 * 3600
    memory_efficiency: "90% reduction"

# Component-Specific Targets
component_targets:
  # Fusion Engine Performance
  fusion_engine:
    aho_corasick:
      chars_per_sec: 50000000    # 50M chars/sec
      patterns_per_sec: 1000000  # 1M pattern matches/sec
      memory_usage_mb: 100       # 100MB memory footprint
      
    flpc_rust:
      chars_per_sec: 69000000    # 69M chars/sec (proven)
      patterns_per_sec: 500000   # 500K pattern matches/sec
      memory_usage_mb: 200       # 200MB memory footprint
      
    pattern_router:
      routing_decisions_per_sec: 100000  # 100K decisions/sec
      routing_accuracy: 0.95     # 95% accuracy
      overhead_percentage: 2     # 2% overhead
  
  # Pipeline Component Targets
  pipeline:
    conversion:
      pages_per_sec: 1000        # PDF to Markdown
      memory_per_page_kb: 50     # 50KB per page
      
    classification:
      pages_per_sec: 10000       # 5x faster than MVP-Hyper
      entities_per_sec: 1000000  # 1M entities/sec
      accuracy: 0.98             # 98% accuracy maintained
      
    enrichment:
      pages_per_sec: 8000        # Targeted enrichment
      enrichment_rate: 0.95      # 95% documents enriched
      
    extraction:
      pages_per_sec: 1000        # Semantic extraction
      facts_per_sec: 10000       # 10K facts/sec

# Memory Performance Targets
memory_targets:
  # Zero-copy operations
  zero_copy_efficiency: 0.9     # 90% operations zero-copy
  
  # Memory usage per document
  small_docs_kb: 10             # <1MB documents: 10KB memory
  medium_docs_kb: 50            # 1-10MB documents: 50KB memory  
  large_docs_kb: 100            # >10MB documents: 100KB memory
  
  # Memory pool efficiency
  pool_hit_rate: 0.95           # 95% memory pool hits
  pool_fragmentation: 0.05      # 5% fragmentation max
  
  # Garbage collection
  gc_frequency_docs: 1000       # GC every 1000 documents
  gc_pause_time_ms: 10          # 10ms max GC pause

# Throughput Targets by File Type
file_type_targets:
  # Text-heavy documents
  text_documents:
    pages_per_sec: 15000        # Plain text processing
    entities_per_page: 50       # 50 entities per page avg
    
  # PDF documents
  pdf_documents:
    pages_per_sec: 5000         # PDF parsing overhead
    ocr_pages_per_sec: 100      # OCR if needed
    
  # Complex documents (tables, images)
  complex_documents:
    pages_per_sec: 2000         # More processing required
    accuracy_maintenance: 0.98  # Maintain 98% accuracy

# Latency Targets
latency_targets:
  # Single document processing
  small_doc_ms: 10              # <1MB: 10ms
  medium_doc_ms: 50             # 1-10MB: 50ms
  large_doc_ms: 200             # >10MB: 200ms
  
  # Batch processing
  batch_startup_ms: 100         # Batch initialization
  batch_processing_ms: 500      # Process 32 docs in 500ms
  
  # Pattern matching
  pattern_match_us: 100         # 100 microseconds per pattern
  routing_decision_us: 10       # 10 microseconds routing decision

# Scalability Targets
scalability_targets:
  # Concurrent processing
  max_concurrent_batches: 8     # 8 batches simultaneously
  documents_per_batch: 32       # 32 documents per batch
  
  # Worker scaling
  linear_scaling_workers: 16    # Linear scaling up to 16 workers
  scaling_efficiency: 0.8       # 80% efficiency at max scale
  
  # Memory scaling
  memory_per_worker_mb: 1024    # 1GB per worker max
  total_memory_scaling_gb: 16   # 16GB total at max scale

# Quality Targets (No Degradation)
quality_targets:
  # Classification accuracy
  classification_accuracy: 0.98  # Maintain 98% accuracy
  entity_extraction_recall: 0.95 # 95% entity recall
  entity_extraction_precision: 0.97 # 97% entity precision
  
  # Output compatibility
  output_format_compatibility: 1.0  # 100% format compatibility
  metadata_preservation: 1.0        # 100% metadata preservation
  
  # Error rates
  processing_error_rate: 0.01       # 1% max error rate
  corruption_rate: 0.001            # 0.1% max corruption rate

# Benchmark Validation Targets
benchmark_targets:
  # Regression testing
  performance_regression_threshold: 0.05  # 5% max regression
  quality_regression_threshold: 0.01      # 1% max quality regression
  
  # Continuous improvement
  monthly_improvement_target: 0.1          # 10% monthly improvement
  optimization_cycle_days: 30             # Monthly optimization cycles
  
  # Stress testing
  stress_test_duration_hours: 24          # 24-hour stress tests
  stress_test_throughput_maintenance: 0.9 # 90% throughput under stress